data_root_dir: /project/aip-aspuru/aburger/fairchem-esen/checkpoint
run_dir: /scratch/aburger/checkpoint/uma
account: ocp
qos: ocp
mode: SLURM
device: CUDA
ranks_per_node: 1
dataloader_workers: 4
debug: False
mem_gb: 0
cpus_per_task: 24

